### ISSUE TITLE
are emails set to be unique? can't create multiple accounts for one email. especially if we're taking out workspaces

### ISSUE THREAD

**Issue by sai-sy** [chester-hill-solutions/callcaster#140]

**Comment by manstephen** [comment]
Yes, but default Supabase enforces unique emails on auth.users. On top of this, the "username" column on public.users is UNIQUE; since all "usernames" going forward will just be the email the user sign ups with, this will also prevent users from signing up with the same email. 
![image](https://github.com/chester-hill-solutions/callcaster/assets/56130056/1d56b7ae-1c30-44b8-8793-b1113ca28224)

**Comment by sai-sy** [comment]
Moving forward could we phase out any mention of username, user name, etc?
