### ISSUE TITLE
Use Custom Claims & Role-based Access Control (RBAC)

### ISSUE THREAD

**Issue by wra-sol** [chester-hill-solutions/callcaster#23]
We should manage workspace access with a claim in the user's access token.

This will eliminate the need for the redundant 'user' table, and enable faster transactions.

Specific requirements: 

- Workspace creation must be included for self-created users. 
> Flow: Sign Up -> Confirm Personal Details -> Create Organization (and create workspace claim + sudo claim) -> Dashboard

- Access level must be set by the inviter, and can only be as high as their own. Claims included on initial creation
> Flow: Admin in dashboard -> Creates new user with specific auth level (claim is set on invite) -> invite is confirmed by user -> User creates new password and confirms personal details -> Dashboard

Reference Docs: https://supabase.com/docs/guides/database/postgres/custom-claims-and-role-based-access-control-rbac 

OR 

https://supabase.com/docs/guides/auth/managing-user-data

**Comment by manstephen** [comment]
Okay the infrastructure for RBAC (the role enum, permission enum, and Auth Hook) have all been setup. A user's role information can now be accessed by decoding the serverSession.access_token with jwt-decode:
```
if (serverSession) {
    const jwt = jwtDecode(serverSession.access_token);
    const userRole = jwt["user_workspace_role"];

    const hasAccess = userRole === "member";

    return json({ hasAccess: hasAccess, userRole }, { headers });
  }
```
Next step is to move RLS checks from comparing a user's uuid against a workspace's users array to checking the user's role in the relational workspace_users table. Additionally, the workspace_permissions table is an exhaustive list of each permission available to users on the workspace - each row should be completely unique. This table is pluralized because workspace_permission is the name of the enum.

**Comment by manstephen** [comment]
RBAC is up and running and should be fully functioning although some more case by case testing is required. Notably, to use RBAC in an RLS policy you must use the `authorize(workspace_id uuid, requested_permission workspace_permission)` function. Therefore you MUST SELECT a workspace_id associated with whatever table you are trying to access for RBAC to work. This makes sense since we are implementing these permissions on a workspace-basis. Permissions can be added by changing the workspace_permission ENUM and role permissions can be changed in the workspace_permissions TABLE. Please note every row in workspace_permissions is a unique combination of (workspace_role, workspace_permission)
